### PR TITLE
Rename BSON::EDC-Tools to BSON::EDCTools to work round panda

### PR DESCRIPTION
**Pull request by jonathanstowe**
Hi,
I think probably the best solution is to fix the Panda::Builder so that it won't ignore module names with a '-' in, but this should get you started again.

### CODE REVIEW

**Comment by jonathanstowe** [comment]
Hi,
I made https://github.com/tadzik/panda/pull/197 - when that gets pulled it won't be necessary

**Comment by MARTIMM** [comment]
I already made changes to BSON and it installs alright now. The MongoDB module  which depends on it is also modified to reflect the changes and installs fine.

**Comment by jonathanstowe** [comment]
I'll close the PR :-)  Nice work

**Comment by jonathanstowe** [comment]
Not necessary any more :)

**Pull request closed without merging**
